### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by josefnpat** [asswb/game-off-2012#50]

**Comment by josefnpat** [comment]
Need to research how to migrate the old repos to point to new address.

**Comment by DreadKnight** [comment]
Is there a newer repo? It's pretty easy to rename a GitHub project nowadays from it's settings.

**Comment by josefnpat** [comment]
haha, thanks @DreadKnight - I have no idea what this ticket means anymore.

**Comment by DreadKnight** [comment]
I'm guessing you wanted to give it a more custom name instead of the one forced by the competition xD
